In [1]:
## CNN Example

In [2]:
import numpy as np

In [3]:
## The sigmoid activation function
def sigmoid(z):
	return 1.0/(1.0+np.exp(-z))

In [4]:
## Derivative of the sigmoid activation function
def sigmoid_prime(z):
	return sigmoid(z)*(1-sigmoid(z))

In [5]:
## Forward Convolution
def conv_forward(X, W):
    '''
    The forward computation for a convolution function
    
    Arguments:
    X -- output activations of the previous layer, numpy array of shape (n_H_prev, n_W_prev) assuming input channels = 1
    W -- Weights, numpy array of size (f, f) assuming number of filters = 1
    
    Returns:
    H -- conv output, numpy array of size (n_H, n_W)
    cache -- cache of values needed for conv_backward() function
    '''
    
    # Retrieving dimensions from X's shape
    (n_H_prev, n_W_prev) = X.shape
    
    # Retrieving dimensions from W's shape
    (f, f) = W.shape
    
    # Compute the output dimensions assuming no padding and stride = 1
    n_H = n_H_prev - f + 1
    n_W = n_W_prev - f + 1
    
    # Initialize the output H with zeros
    H = np.zeros((n_H, n_W))
    
    # Looping over vertical(h) and horizontal(w) axis of output volume
    for h in range(n_H):
        for w in range(n_W):
            x_slice = X[h:h+f, w:w+f]
            H[h,w] = np.sum(x_slice * W)
            
    # Saving information in 'cache' for backprop
    cache = (X, W)
    
    return H, cache

In [6]:
## Backward Convolution
def conv_backward(dH, cache):
    '''
    The backward computation for a convolution function
    
    Arguments:
    dH -- gradient of the cost with respect to output of the conv layer (H), numpy array of shape (n_H, n_W) assuming channels = 1
    cache -- cache of values needed for the conv_backward(), output of conv_forward()
    
    Returns:
    dX -- gradient of the cost with respect to input of the conv layer (X), numpy array of shape (n_H_prev, n_W_prev) assuming channels = 1
    dW -- gradient of the cost with respect to the weights of the conv layer (W), numpy array of shape (f,f) assuming single filter
    '''
    
    # Retrieving information from the "cache"
    (X, W) = cache
    
    # Retrieving dimensions from X's shape
    (n_H_prev, n_W_prev) = X.shape
    
    # Retrieving dimensions from W's shape
    (f, f) = W.shape
    
    # Retrieving dimensions from dH's shape
    (n_H, n_W) = dH.shape
    
    # Initializing dX, dW with the correct shapes
    dX = np.zeros(X.shape)
    dW = np.zeros(W.shape)
    
    # Looping over vertical(h) and horizontal(w) axis of the output
    for h in range(n_H):
        for w in range(n_W):
            dX[h:h+f, w:w+f] += W * dH[h,w]
            dW += X[h:h+f, w:w+f] * dH[h,w]
    
    return dX, dW

In [8]:
#######################################################################

In [9]:
# The input data
X = np.asarray([[0.1,0.2,1.3],[0.37,1.09,1.02],[0.12,-0.23,-0.45]])

In [21]:
X

array([[ 0.1 ,  0.2 ,  1.3 ],
       [ 0.37,  1.09,  1.02],
       [ 0.12, -0.23, -0.45]])

In [10]:
# Weights
W = np.asarray([[0.4,-0.1],[0.23,0.61]])

In [22]:
W

array([[ 0.4 , -0.1 ],
       [ 0.23,  0.61]])

In [15]:
# Forward convolution
Z, data_cache = conv_forward(X, W)

In [20]:
data_cache

(array([[ 0.1 ,  0.2 ,  1.3 ],
        [ 0.37,  1.09,  1.02],
        [ 0.12, -0.23, -0.45]]), array([[ 0.4 , -0.1 ],
        [ 0.23,  0.61]]))

In [16]:
Z

array([[ 0.77  ,  0.8229],
       [-0.0737,  0.0066]])

In [12]:
# Activation
H = sigmoid(Z)

In [17]:
H

array([[ 0.68352089,  0.69485158],
       [ 0.48158334,  0.50164999]])

In [ ]:
# Backward pass

In [13]:
dH = sigmoid_prime(Z)

In [19]:
dH

array([[ 0.21632008,  0.21203286],
       [ 0.24966083,  0.24999728]])

In [14]:
# Backward convolution
dX, dW = conv_backward(dH, data_cache)

In [23]:
dW

array([[ 0.42891012,  0.84603426],
       [ 0.28361417,  0.28214164]])

In [24]:
dX

array([[ 0.08652803,  0.06318114, -0.02120329],
       [ 0.14961795,  0.25575564,  0.10434032],
       [ 0.05742199,  0.20979248,  0.15249834]])